### ISSUE TITLE
Q: Delete empty board

### ISSUE THREAD

**Issue by lowprize** [decole/planka-php-sdk#16]
How can I delete empty boards (created while testing api) ?

$projects = $client->project->list();
foreach ($projects as $project) {
    $boards = $client->board->list($project->id);
    if (empty($boards)) {
        $client->project->delete($project->id);
        echo "Projekt ID " . $project->id . " Deleted";
    }
}

It doesn't work

**Comment by decole** [comment]
my wrapper executes the requests that Planka makes over the web socket. 
Did you look at the test file? `/test/index.php` 

$boards = $client->board->list($project->id);

you will get your DTO back - ProjectListDto - you have to work as with an object.

ProjectListDto - wrapper for response Planka on project list entrypoint

To find out that a project has empty boards, you need to request a list of boards from each project and ask the boards for their data.

**Comment by decole** [comment]
```php
        // Only projects and boards assigned to your user are available
        $dto = $client->project->list();

//        dd($dto->items); // list projects

        // the list will only contain boards available to your user
        $boards = $dto->included->boards;

        /** @var BoardItemDto $item */
        foreach ($boards as $item) {
            // we request each board separately
            $board = $client->board->get($item->id);

            // list of board cards
            $cardList = $board->included->cards;

            if (empty($cardList)) {
                // removing a board without cards
                $client->board->delete($item->id);
            }
        }
```

**Comment by decole** [comment]
If there are no more questions. I'll close issue in a next week.

**Comment by decole** [comment]
> Thx I'll try, I am missing docs and I learnig by test-fail-again :)

What did you want to do? Maybe I can guide you on the right path?

**Comment by lowprize** [comment]
Thank you for your offer. I'll try make button in my IS. The button create new card in one specific list (name or ID) with description, attachment etc. 
Im also testing your test file, but it stops while Im try upload attachment (image.png). Is it works for you?

**Comment by decole** [comment]
I'll check the test file. I haven't worked on this repository for a long time. I have a repository where I created a card in a specific board for example

https://github.com/decole/planka-automata/blob/main/src/Feature/SentryWebhook/Service/CreateBugfixCardService.php

**Comment by decole** [comment]
And what documentation is missing, I'll try to write it over the weekend
