### ISSUE TITLE
Board List Class is missing

### ISSUE THREAD

**Issue by drascom** [decole/planka-php-sdk#21]
hey, thank you for this rare work. i am try to create a small app with 2 dependent selectbox to select specific bord from specific project.there is list controller for projects but no board list function to list them for selected project. is there a simple way to add that ? other way it is impossible to know board id to list the cards.
here is the board controller 
<img width="911" alt="image" src="https://github.com/user-attachments/assets/81f970ae-b211-4b53-95bb-e3b0bdaededc">
and here is the BoardList controller 
<img width="926" alt="image" src="https://github.com/user-attachments/assets/517c1ff4-1f08-48c3-9fa5-0582559873fa">
 we need a list fonction like project controller has.
thank you

**Comment by decole** [comment]
This library is a simple wrapper over Plank. you will have to act as Planck herself does.

I made a wrapper over the Planka API, nothing more. You will have to figure out how Planka works with projects and boards. See the example of a websocket on your Planka site.

all the entrypoints that I wrapped are under the hood of the Planka project. https://github.com/plankanban/planka/blob/master/server/config/routes.js


// Only projects and boards assigned to your user are available
$dto = $planka->project->list();

See websocket on Planka website

![image](https://github.com/user-attachments/assets/fcd70720-e208-40f9-908d-671f1a1a053c)

Planka does:
1. Get projects
2. Foreach body params

![image](https://github.com/user-attachments/assets/1b2225a1-eb59-458c-8304-b5181a199fa9)




See for example - [Example - Delete empty board](https://github.com/decole/planka-php-sdk?tab=readme-ov-file#example---delete-empty-board)

**Comment by decole** [comment]
Closer to winter I will have time. I will try to make documentation with examples. But it will be faster for you to understand what and how Plank requests via websocket and how it processes data

**Comment by drascom** [comment]
okay i get it // Only projects and boards assigned to your user are available mean i need to use user id to fatch related boards 
also i understand you just wrote wrapper around existing avaliable routes.
But
in https://github.com/plankanban/planka/tree/master/server/api/controllers/projects)
/show.js file there is a line of code like  
`  let boards = await sails.helpers.projects.getBoards(project.id);
    let boardIds = sails.helpers.utils.mapRecords(boards);`
line 31 & 32. i am very rusty about php but maybe you can find a way to reach this ability.

**Comment by decole** [comment]
You log in and based on which boards you have access to, you will only get them.

/show.js file there is a line of code like 

I don't really know much about JS.

**Comment by decole** [comment]
I can only help in winter because the country where I live is not calm now and I try to enjoy life before I am mobilized

**Comment by drascom** [comment]
i found a way to get all boards belong to user  boardMembership query returns with necessary details let me try to filter it. thank you for quick response also for your hardwork to create this sdk.

<img width="923" alt="image" src="https://github.com/user-attachments/assets/43395a5c-fd93-4329-b261-3c7cd30d4c3e">

**Comment by drascom** [comment]
i know i closed to issue but i found a way to get boards by project name in plankapy project 
it get s all boards by project name (only the projects belong to user)
`def get(
	self,
	project_name: str = None,
	board_name: str = None,
	oid: str = None
) -> dict:
Gets a board by name

oid: ID of board to get (optonal)
name: Name of board if None returns all boards
project_name: Name of project to get boards from
return: GET response dictionary`

we should have a way to get response from `'POST /api/projects/:projectId/boards'`
