### ISSUE TITLE
No entry for card subscriptions

### ISSUE THREAD

**Issue by capitaineflam25** [decole/planka-php-sdk#22]
I wanted to get card subscriptions through the API to manage my own notifications.

I'm creating this issue but i think the API for card subscriptions is missing in the main Planka project.

**Comment by decole** [comment]
ok, I'll have a look at the end of the week

**Comment by decole** [comment]
https://github.com/plankanban/planka/blob/master/server/config/routes.js

**Comment by decole** [comment]
> I wanted to get card subscriptions through the API to manage my own notifications.
> 
> I'm creating this issue but i think the API for card subscriptions is missing in the main Planka project.

Added subscription and unsubscription entrypoints.
I looked, the answers in some places of the Planka may have changed a little. As soon as I have some free time, I'll update everything.

You can see the changes in version 1.2.0. Please update.

**Comment by eedomus** [comment]
Wow ! Amazing work ! Thanks.
